Complete CRUD with ExerciseType entity
Kosiv92/IG_Train pull request #1
Opened 2024-03-11 05:41 UTC by Kosiv92

2024-03-11 08:53 UTC, ilyanikolaeff commented on src/IG_Train.Contracts/Responses/ExerciseTypeResponse.cs
> +public record ExerciseTypeResponse
Сделай чере дефолт конструктор

2024-03-11 08:53 UTC, ilyanikolaeff commented on src/IG_Train.Domain/Repositories/IRepository.cs
> +    public Task<TKey> CreateAsync(TEntity entity, CancellationToken cancellationToken = default);
Не делай default CancellationToken, пусть везде пробрасывается

2024-03-11 08:53 UTC, ilyanikolaeff commented on src/IG_Train.Domain/Services/IExerciseTypeService.cs
> +    Task DeleteExerciseType(int id, CancellationToken cancellationToken = default);
Аналогично с дефолт токеном

2024-03-11 08:53 UTC, ilyanikolaeff commented on test/IG_Train.Tests.Unit/Application/Validators/CreateExerciseTypeRequestValidatorTests.cs
> +namespace IG_Train.Tests.Unit.Application.Validators
Тесты на свои сервисы

2024-03-14 16:49 UTC, ilyanikolaeff requested changes
Как пофиксишь отпиши общим комментом

2024-03-14 16:49 UTC, ilyanikolaeff commented on src/IG_Train.Application/Handlers/ExerciseType/Create/CreateExerciseTypeHandler.cs
> +            (new ExerciseTypeEntity(default, request.Name, request.Description), cancellationToken));
Не стоит создание сущности пихать в хендлер, делегируй в сервис. Идеальный флоу хендлер -> сервис, при этом в хендлере ничего кроме перенаправления запроса

2024-03-14 16:49 UTC, ilyanikolaeff commented on src/IG_Train.Application/Mapping/ApplicationMappingProfile.cs
> +        CreateMap<UpdateExerciseTypeRequest, ExerciseTypeEntity>();
Хороший стиль маппинг расписывать по мемберам

2024-03-14 16:49 UTC, ilyanikolaeff commented on src/IG_Train.Application/Validators/CreateExerciseTypeRequestValidator.cs
> +            .WithMessage(x => $"{nameof(x.Name)} must not be null or empty");
Это я писал? 
Если я, то есть еще тема без интерполяции {PropertyName} в строке и FluentValidation автоматом проставит

2024-03-14 16:49 UTC, ilyanikolaeff commented on src/IG_Train.Domain/Entities/ExerciseTypeEntity.cs
> +    public string Name { get; private set; }
Пока не ДДД можно без приватных сеттеров, но я не помню точно поддерживает ли EFCore такие приколы (вроде да)

2024-03-14 16:49 UTC, ilyanikolaeff commented on src/IG_Train.Domain/Services/ExerciseTypeService.cs
> +        private readonly IRepository<ExerciseTypeEntity, int> _repositoryET;
Имя переменной шлак

2024-03-16 15:06 UTC, Kosiv92 commented on src/IG_Train.Domain/Entities/ExerciseTypeEntity.cs
> +    public string Name { get; private set; }
EF Core приватные сеттеры поддерживает. Я думаю, что если по какой-то причине не требуется обратное, то лучше ограничить запись новых значений в свойства

2024-03-16 15:19 UTC, Kosiv92 commented on src/IG_Train.Application/Handlers/ExerciseType/Create/CreateExerciseTypeHandler.cs
> +            (new ExerciseTypeEntity(default, request.Name, request.Description), cancellationToken));
В настоящий момент проект Domain не ссылается на проект Application, где определены request и response классы, соответственно тут либо добавлять из Domain ссылку на Application и тогда я из сервисам смогу возвращать необходимые объекты (что как я понимаю в корен неправильный подход), либо выделять еще одни сервис который будет заниматься созданием таких объектов

2024-03-20 11:34 UTC, ilyanikolaeff commented on src/IG_Train.Application/Validators/CreateExerciseTypeRequestValidator.cs
> +        .NotEmpty()
NotEmpty покрывает NotNull, можешь в доке убедиться

2024-03-20 11:37 UTC, ilyanikolaeff commented on src/IG_Train.Web/Controllers/ExerciseTypeController.cs
> +            => await _mediator.Send(request, cancellationToken);
А в чем смысл async/await делать если можно просто прокинуть, без лишней инициализации стейт машины. Перформанс минимальный, а букв меньше

2024-03-20 11:37 UTC, ilyanikolaeff commented on src/IG_Train.Web/Extensions/ServiceCollectionExtensions.cs
> +        services.AddFluentValidationAutoValidation();
Это точно из SharpGrip подключено? смущает юзинг на второй строке

2024-03-20 11:37 UTC, ilyanikolaeff commented on test/IG_Train.Tests.Unit/Application/Validators/UpdateExerciseTypeRequestValidatorTests.cs
> +            var result = sut.Validate(request);
TestValidateAsync

2024-03-20 11:37 UTC, ilyanikolaeff commented on test/IG_Train.Tests.Unit/Application/Validators/UpdateExerciseTypeRequestValidatorTests.cs
> +            var result = sut.Validate(request);
Аналогично

2024-03-20 14:29 UTC, Kosiv92 commented on src/IG_Train.Web/Controllers/ExerciseTypeController.cs
> +            => await _mediator.Send(request, cancellationToken);
В дальнейшем я могу добавить еще поля для этой сущности, добавить подгрузку картинки или еще как то изменить реализацию таким образом, что блокировка потока будет занимать заметное время. Понимаю, что возможно в данном случае я ничего не экономлю, но хотелось бы придерживаться единого стиля и по возможности использовать асинхронные операции

2024-03-21 09:12 UTC, ilyanikolaeff commented on src/IG_Train.Web/Controllers/ExerciseTypeController.cs
> +            => await _mediator.Send(request, cancellationToken);
Ну как будет, так и расширишь

2024-03-21 14:36 UTC, ilyanikolaeff approved these changes

2024-03-21 14:39 UTC, merged